name: CI for Java Invoice
on: [push]
jobs:
  lint:
    name: Check code with checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Checkstyle
        run: mvn checkstyle:check
  test:
    strategy:
      matrix:
        version: [ 13, 15 ]
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          distribution: 'adopt'
      - name: Test
        run: mvn test